version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  flask-app:
    build: ./backend
    container_name: flask-app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
    networks:
      - elastic

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://flask-app:5000
    depends_on:
      - flask-app
    networks:
      - elastic

networks:
  elastic:
    driver: bridge