version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge